accounting_management/urls.py
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import include, path

from requests_mgmt.views import HomeView
from users_mgmt.views import LoginView, LogoutView, RegisterView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("iniciar-sesión/", LoginView.as_view(), name="login"),
    path("registrarse/", RegisterView.as_view(), name="register"),
    path("cerrar-sesión/", login_required(LogoutView.as_view()), name="logout"),
    path("", login_required(HomeView.as_view()), name="home"),
    path("usuarios/", include("users_mgmt.urls")),
    path("solicitudes/", include("requests_mgmt.urls")),
]

requests_mgmt/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from .views import (
    SearchRequestView,
    AdvanceRequest,
    AdvanceRequestView,
    ChargeAccountView,
    DeleteRequestView,
    DetailsRequestView,
    EditRequestView,
    HomeView,
    InvoiceLegalizationView,
    RequestsListView,
    RequestsMadeView,
    RequestsView,
    TravelExpensesRequest,
    UpdateApproverView,
    UpdateReviewerView,
    RequestExpenses,
    SetClosingDate,
    InvoicesRequestView
)

urlpatterns = [
    path(
        "", 
        login_required(RequestsListView.as_view()), 
        name="requests_list", 
        ),
    path(
        "<int:request_id>",
        login_required(DetailsRequestView.as_view()),
        name="detail_request",
    ),
    path("search/<str:requester>", login_required(SearchRequestView.as_view()),name="search_request"),
    path(
        "update_reviewer/<int:request_id>",
        login_required(UpdateReviewerView.as_view()),
        name="update_reviewer",
    ),
    path(
        "update_approver/<int:request_id>",
        UpdateApproverView.as_view(),
        name="update_approver",
    ),
    path(
        "<int:request_id>/eliminar",
        login_required(DeleteRequestView.as_view()),
        name="delete_request",
    ),
    path("nueva", login_required(RequestsView.as_view()), name="requests_index"),
    path(
        "nueva/cuenta de cobro",
        login_required(ChargeAccountView.as_view()),
        name="charge_account",
    ),
    path(
        "nueva/legalizacion de facturas",
        login_required(InvoiceLegalizationView.as_view()),
        name="invoice_legalization",
    ),
    
    path(
        "nueva/anticipos",
        login_required(AdvanceRequestView.as_view()),
        name="advance_request",
    ),
    path(
        "<int:request_id>/nuevo gasto",
        login_required(RequestExpenses.as_view()),
        name="request_expense",
    ),
    path(
        "nueva/viaticos",
        login_required(TravelExpensesRequest.as_view()),
        name="travel_expenses",
    ),
    path("nueva/facturas",
         login_required(InvoicesRequestView.as_view()),
         name="invoice"),
    path(
        "mis solicitudes",
        login_required(RequestsMadeView.as_view()),
        name="requests_made",
    ),
    path(
        "<int:request_id>/Cierre",
        login_required(SetClosingDate.as_view()),
        name="set_closing_date",
    ),
    
]

users_mgmt/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from .views import (
    AssignRolesView,
    SearchUsersView,
    ApproveAsApproverView,
    ApproveAsReviewerView,
)

urlpatterns = [
    path("roles/", login_required(AssignRolesView.as_view()), name="assign_roles"),
    path("", login_required(SearchUsersView.as_view()), name="search_users"),
    path(
        "roles/aprobador",  # Deberia estar en requests_mgmt ???
        login_required(ApproveAsApproverView.as_view()),
        name="approve_as_approver",
    ),
    path(
        "roles/revisores",  # Deberia estar en requests_mgmt ???
        login_required(ApproveAsReviewerView.as_view()),
        name="approve_as_reviewer",
    ),
]

requests_mgmt/models/advance_request.py
from django.db import models
from django.views import View

from .request import Request

class AdvanceRequest(Request):
    request_date = models.DateField(null=True,blank=True)
    dependency = models.CharField(default='Not Set',max_length=200)

    destination_city =models.CharField(default='Not Set',max_length=200)

    departure_date=models.DateField(null=True,blank=True)

    return_date=models.DateField(null=True,blank=True)

    reason_trip=models.CharField(default='Not Set',max_length=200)

    advance_currency = models.CharField(default='Not Set',max_length=200)

    icesi_last_day_date=models.DateField(null=True,blank=True)

    payment_order_code=models.CharField(default='Not Set',max_length=200)

    airport_transport = models.FloatField(default=0)
    local_transport = models.FloatField(default=0)
    feeding = models.FloatField(default=0)
    accommodation = models.FloatField(default=0)
    departure_taxes = models.FloatField(default=0)
    others = models.FloatField(default=0)
    
    widget = models.FloatField(default=0)

    document_path = models.CharField(default='',max_length=350)

requests_mgmt/models/invoice_legalization_request.py
from django.db import models

from .request import Request


class InvoiceLegalizationRequest(Request):
    legalization_date = models.DateField(default='2000-01-01')
    dependency = models.CharField(default='Not Set',max_length=200)

    destination_city =models.CharField(default='Not Set',max_length=200)

    departure_date=models.DateField(default='2000-01-01')

    reason_trip=models.CharField(default='Not Set',max_length=200)

    discount_authorization = models.CharField(default='Not Set',max_length=5)

    bank_name = models.CharField(default="Not Set", max_length=20)
    account_type = models.CharField(default="Not Set", max_length=20)
    account_number = models.CharField(default="Not Set", max_length=20)
    document_path = models.CharField(default='',max_length=350)

requests_mgmt/models/request_status.py
from django.db import models


class RequestStatus(models.Model):
    status = models.CharField(max_length=100)

requests_mgmt/forms/add_approver.py
from django import forms

from users_mgmt.models import CustomUser as User, Roles


class AddApproverForm(forms.Form):
    # request_id = forms.IntegerField(widget=forms.HiddenInput())
    # type = forms.CharField(widget=forms.HiddenInput())
    approvers = forms.ChoiceField(required=False, label="")

    def __init__(self, *args, **kwargs):
        selected_approver_id = kwargs.pop("selected_approver_id", None)
        super(AddApproverForm, self).__init__(*args, **kwargs)
        approver_role = Roles.objects.get(name="aprobador")
        approvers = User.objects.filter(role=approver_role)
        approver_choices = [(0, "Selecione un aprobador")] + [
            (approver.id, approver) for approver in approvers
        ]
        self.fields["approvers"].choices = approver_choices

        if selected_approver_id:
            self.fields["approvers"].initial = selected_approver_id


# class AddApproverForm(forms.Form):
#     approver_role = Roles.objects.get(name="aprobador")
#     approvers = User.objects.filter(role=approver_role)
#     approver_choices = [(approver.id, approver) for approver in approvers]
#     selected_approver_id = forms.ChoiceField(choices=approver_choices, required=False)

requests_mgmt/forms/add_reviewer.py
from django import forms

from users_mgmt.models import CustomUser as User, Roles


class AddReviewerForm(forms.Form):
    # request_id = forms.IntegerField(widget=forms.HiddenInput())
    # type = forms.CharField(widget=forms.HiddenInput())
    reviewers = forms.ChoiceField(required=False, label="")

    def __init__(self, *args, **kwargs):
        selected_reviewer_id = kwargs.pop("selected_reviewer_id", None)
        super(AddReviewerForm, self).__init__(*args, **kwargs)
        reviewer_role = Roles.objects.get(name="revisor")
        reviewers = User.objects.filter(role=reviewer_role)
        reviewer_choices = [(0, "Selecione un revisor")] + [
            (reviewer.id, reviewer) for reviewer in reviewers
        ]
        self.fields["reviewers"].choices = reviewer_choices

        if selected_reviewer_id:
            self.fields["reviewers"].initial = selected_reviewer_id


# class AddReviewerForm(forms.Form):
#     reviewer_role = Roles.objects.get(name="revisor")
#     reviewers = User.objects.filter(role=reviewer_role)
#     reviewer_choices = [(reviewer.id, reviewer) for reviewer in reviewers]
#     selected_reviewer_id = forms.ChoiceField(choices=reviewer_choices, required=False)

requests_mgmt/forms/advance_request.py
from django import forms   

class AdvanceRequest(forms.Form):

    request_date = forms.DateField(label = 'Fecha de solicitud', widget=forms.DateInput(attrs={"class": "form-control", "type": "date"}),)

    dependency = forms.CharField(label = "Dependencia: ",max_length=200, widget=forms.TextInput(attrs={"class": "form-control"}))

    destination_city = forms.CharField(label = "Ciudad de destino: ",max_length=200, widget=forms.TextInput(attrs={"class": "form-control"}))
    
    departure_date = forms.DateField(
        label="Fecha de salida: ",
        widget=forms.DateInput(attrs={"class": "form-control", "type": "date"}),
    )

    return_date = forms.DateField(
        label="Fecha de regreso: ",
        widget=forms.DateInput(attrs={"class": "form-control", "type": "date"}),
    )

    reason_trip = forms.CharField(
    label="Motivo de viaje:",
    widget=forms.Textarea(attrs={"class": "form-control", "rows": 6}))

    advance_currency = forms.ChoiceField(label='Moneda', choices=[('Pesos colombianos', 'Pesos colombianos'), ('Dólares', 'Dólares'), ('Euros', 'Euros')], widget=forms.Select(attrs={'class': 'form-control'})) 

    icesi_last_day_date = forms.DateField(
        label="Indique el último día que estará en Icesi antes de su viaje: ",
        widget=forms.DateInput(attrs={"class": "form-control", "type": "date"}),
    )


class ExpenseBudget(forms.Form):

    airport_transport = forms.CharField(label = "Transporte Aereopuerto: ",max_length=200, widget=forms.TextInput(attrs={"class": "form-control"}))

    local_transport = forms.CharField(label = "Transporte local: ",max_length=200, widget=forms.TextInput(attrs={"class": "form-control"}))

    feeding = forms.CharField(label = "Alimentación: ",max_length=200, widget=forms.TextInput(attrs={"class": "form-control"}))
    
    accommodation = forms.CharField(label = "Alojamiento: ",max_length=200, widget=forms.TextInput(attrs={"class": "form-control"}))

    departure_taxes = forms.CharField(label = "Impuestos de salida: ",max_length=200, widget=forms.TextInput(attrs={"class": "form-control"}))

    others = forms.CharField(label = "Otros: ",max_length=200, widget=forms.TextInput(attrs={"class": "form-control"}))

requests_mgmt/forms/assign_accounting_maganer.py
from django import forms

from users_mgmt.models import CustomUser as User


class AssignManagerForm(forms.Form):
    manager = forms.ModelChoiceField(
        queryset=User.objects.filter(role__name="gestor de contabilidad"),
        widget=forms.Select(attrs={"class": "role-select"}),
    )

requests_mgmt/forms/bank_information.py
from django import forms


class BankInformation(forms.Form):
    CHOICES = [("<Seleccione tipo de cuenta>", "<Seleccione tipo de cuenta>"),("corriente", "Corriente"), ("ahorro", "Ahorro")]
    bank_name = forms.CharField(
        label="Banco: ",
        max_length=200,
        widget=forms.TextInput(attrs={"class": "form-control"}),
    )
    account_number = forms.CharField(label="Numero de Cuenta : ", max_length=200, widget=forms.TextInput(attrs={"class": "form-control"}))

    account_type = forms.ChoiceField(
        label="Tipo de cuenta: ", choices=CHOICES, widget=forms.Select(attrs={'class': 'form-control'})
    )
    cex_no = forms.CharField(label="CEX No : ", max_length=200, widget=forms.TextInput(attrs={"class": "form-control"}))

requests_mgmt/forms/charge_account.py
from django import forms


class ChargeAccountForm(forms.Form):
    DOCUMENT_CHOICES = [
        ("CC", "Cédula de ciudadanía"),
        ("TI", "Tarjeta de identidad"),
        ("CE", "Cédula de extranjería"),
    ]
    user_name = forms.CharField(
        label="Nombre de solicitante:",
        max_length=200,
        widget=forms.TextInput(attrs={"class": "form-control"}),
    )
    user_id = forms.CharField(
        label="Identificación solicitante (C.C.):",
        max_length=200,
        widget=forms.TextInput(attrs={"class": "form-control"}),
    )
    document_type = forms.ChoiceField(
        label="Tipo de documento:",
        choices=DOCUMENT_CHOICES,
        widget=forms.Select(attrs={"class": "form-control"}),
    )
    amount = forms.DecimalField(
        label="Monto $",
        max_digits=10,
        decimal_places=2,
        widget=forms.NumberInput(attrs={"class": "form-control"}),
    )
    concept = forms.CharField(
        label="Concepto:", widget=forms.Textarea(attrs={"class": "form-control"})
    )
    CHOICES = [
        (
            "392_401",
            "Retención en la fuente artículos 392 y 401 del Estatuto Tributario",
        ),
        ("383", "Retención en la fuente artículo 383 del Estatuto Tributario"),
    ]
    checkbox_choices = forms.ChoiceField(
        label="Se tomarán costos y deducciones asociados a las rentas de trabajo por los servicios prestados:",
        choices=CHOICES,
        widget=forms.RadioSelect,
    )
    rent_tax_declarant = forms.BooleanField(
        label="Soy declarante de impuesto de renta", required=False
    )
    fiscal_resident = forms.BooleanField(
        label="Soy residente fiscal en Colombia", required=False
    )
    city = forms.CharField(
        label="Ciudad: ",
        max_length=200,
        widget=forms.TextInput(attrs={"class": "form-control"}),
    )
    date = forms.DateField(
        label="Fecha: ",
        widget=forms.DateInput(attrs={"class": "form-control", "type": "date"}),
    )
    CHOICES = [("corriente", "Corriente"), ("ahorro", "Ahorro")]
    bank_name = forms.CharField(
        label="Banco: ",
        max_length=200,
        widget=forms.TextInput(attrs={"class": "form-control"}),
    )
    account_number = forms.CharField(label="Numero de Cuenta : ")
    account_type = forms.ChoiceField(
        label="Tipo de cuenta: ", choices=CHOICES, widget=forms.RadioSelect
    )
    cex_no = forms.CharField(label="CEX No : ")

requests_mgmt/forms/checkbox_rent_resident.py
from django import forms


class CheckboxRentResidentForm(forms.Form):
    rent_tax_declarant = forms.BooleanField(
        label="Soy declarante de impuesto de renta", required=False
    )
    fiscal_resident = forms.BooleanField(
        label="Soy residente fiscal en Colombia", required=False
    )

requests_mgmt/forms/city_date.py
from django import forms


class CityDateForm(forms.Form):
    city = forms.CharField(
        label="Ciudad: ",
        max_length=200,
        widget=forms.TextInput(attrs={"class": "form-control"}),
    )
    date = forms.DateField(
        label="Fecha: ",
        widget=forms.DateInput(attrs={"class": "form-control", "type": "date"}),
    )

requests_mgmt/forms/documents.py
from django import forms
from django.core.validators import FileExtensionValidator


class UploadDocuments(forms.Form):
    documents = forms.FileField(
        label="Subir documentos",
        required=False,
        widget=forms.ClearableFileInput(attrs={"class": "simple-button"}),
        validators=[FileExtensionValidator(allowed_extensions=["pdf"])],
    )

requests_mgmt/forms/invoice_legalization.py
from django import forms
from django.forms import formset_factory

class InvoiceLegalizationForm(forms.Form):
    legalization_date = forms.DateField(widget=forms.DateInput(attrs={"class": "form-control", "type": "date"}),)

    dependency = forms.CharField(label = "Dependencia: ",max_length=200, widget=forms.TextInput(attrs={"class": "form-control"}))

    destination_city = forms.CharField(label = "Dependencia: ",max_length=200, widget=forms.TextInput(attrs={"class": "form-control"}))

    departure_date = forms.DateField(
        label="Fecha de salida: ",
        widget=forms.DateInput(attrs={"class": "form-control", "type": "date"}),
    )

    reason_trip = forms.CharField(
    label="Motivo de viaje:",
    widget=forms.Textarea(attrs={"class": "form-control", "rows": 6})
)


class ExpenseRatioForm(forms.Form):
    rubro = forms.CharField(label='Rubro', max_length=200, widget=forms.TextInput(attrs={"class": "form-control"}))
    proveedor = forms.CharField(label='Proveedor',max_length=200, widget=forms.TextInput(attrs={"class": "form-control"}))
    nit = forms.CharField(label='Nit', max_length=200, widget=forms.TextInput(attrs={"class": "form-control"}))
    concepto = forms.CharField(label='Concepto', max_length=200, widget=forms.TextInput(attrs={"class": "form-control"}))
    advance_currency = forms.ChoiceField(label='Moneda', choices=[('Pesos colombianos', 'Pesos colombianos'), ('Dólares', 'Dólares'), ('Euros', 'Euros')], widget=forms.Select(attrs={'class': 'form-control'}))
    
    amount = forms.DecimalField(
        label="Monto $",
        max_digits=10,
        decimal_places=2,
        widget=forms.NumberInput(attrs={"class": "form-control"}),
    )


class BalanceDiscountAutorizationForm(forms.Form):
    CHOICES = [('si', 'Sí'), ('no', 'No')]
    autorizar_descuento = forms.ChoiceField(
        label="Autorizo el descuento en una sola cuota en el siguiente pago de nómina",
        choices=CHOICES,
        widget=forms.RadioSelect
    )

class InvoiceLegalizationObservations(forms.Form):
    observations = forms.CharField(label='Observaciones', widget=forms.Textarea(attrs={"class": "form-control", "rows": 10}))

requests_mgmt/templates/requests/create_advance_request.html
{% extends "layouts/base.html"%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} Legalzación de facturas {% endblock %} </title>
</head>
<body>
    {% block content %}
    {% include "sidemenu.html" %}
    <div class="container">
        <h1 class="my-4">Nueva solicitud - Anticipos</h1>
        <div class="my-4">
            <h3>Por favor, tener en cuenta: </h3>
            <ol>
                <li>Los anticipos en moneda nacional deben solicitarse con tres días hábiles antes de la fecha de viaje (como mínimo)</li>
                <li>Los anticipos en moneda extranjera (dólar y euro) deben solicitarse cinco días hábiles antes de la fecha de viaje (como mínimo) </li>
                <li>Todos los soportes de legalización deben venir a nombre de la Universidad Icesi Nit. 890.316.745-5. Documento sin este requisito, será rechazado en la legalización.</li>
            </ol>
        </div>
        <div>
            <form method="POST" class="mb-4" enctype="multipart/form-data"> 
                {% csrf_token %}
                <div class="mx-auto mb-4">
                    <h3>Información del viajero </h3>
                    <div class="row">
                        <div class="col">
                            {{user_info}}
                        </div>
                    </div>
                </div>

                <div class="row mb-4">
                    <div class="col">
                        <div class="form-group">
                            <label for="id_request_date">Fecha de solicitud:</label>
                            {{ advance_request_info.request_date }}
                        </div>
                        <div class="form-group">
                            <label for="id_dependency">Dependencia:</label>
                            {{ advance_request_info.dependency }}
                        </div>
                        <div class="form-group">
                            <label for="id_destination_city">Ciudad de destino:</label>
                            {{ advance_request_info.destination_city }}
                        </div>
                        <div class="form-group">
                            <label for="id_departure_date">Fecha de salida:</label>
                            {{ advance_request_info.departure_date }}
                        </div>
                        <div class="form-group">
                            <label for="id_icesi_last_day_date">Último día en Icesi antes del viaje:</label>
                            {{ advance_request_info.icesi_last_day_date }}
                        </div>
                    </div>
                    <div class="col">
                        <div class="form-group">
                            <label for="id_return_date">Fecha de regreso:</label>
                            {{ advance_request_info.return_date }}
                        </div>
                        <div class="form-group">
                            <label for="id_reason_trip">Motivo de viaje:</label>
                            {{ advance_request_info.reason_trip }}
                        </div>
                        <div class="form-group">
                            <label for="id_advance_currency">Moneda:</label>
                            {{ advance_request_info.advance_currency }}
                        </div>
                        
                    </div>
                </div>

                <div class="mb-4">
                    <h3>Presupuesto de gastos</h3>
                    <div class="form-group">
                        {{ expense_budget }}
                    </div>
                </div>

                <div class="form-group mb-4">
                    <h3>Documentos</h3>
                    {{ upload_documents }}
                </div>
                <div class="text-center">
                    <button type="submit" class="btn btn-success" name="submit_button">Enviar</button>
                </div>
                
            </form>
        </div>
    </div>
    {% endblock %}
</body>
</html>

requests_mgmt/templates/requests/create_invoice_legalization_request.html
{% extends "layouts/base.html"%}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} Legalzación de facturas {% endblock %}</title>
</head>

<body>
    {% block content %}
    {% include "sidemenu.html" %}

    <main class="container mb-5">
        <h1 class="text-center mt-5"> Nueva solicitud - Legalización de facturas </h1>
        <div class="my-4">
            <h3>Por favor, tener en cuenta: </h3>
            <ol>
                <li>Todos los soportes de legalización deben venir a nombre de la Universidad Icesi Nit. 890.316.745-5. Documento sin este requisito, será rechazado en la legalización.</li>
                <li>Si hay saldo es a favor de la Universidad ICESI, se debe regresar el dinero en la caja de la Universidad o autorizar en este formato el descuento por nomina </li>
                <li>Si hay saldo a favor del colaborador, se procede a  reintegrar a la cuenta de nomina </li>
                <li>Si el soporte de pago es una factura Pos, debe solicitar a la empresa la factura electrónica.</li>
                <li>Se debe legalizar en la moneda que se recibió en el anticipo (Pesos colombianos, Euros, Dólares) Si el colaborador gasto en una moneda diferente, debe pasar los gastos a la      moneda original del anticipo y dejar registro del cambio de moneda. </li>
            </ol>
        </div>
        <form method="POST" class="mt-5" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="mb-4">
                <h3>Información del viajero: </h3>
                <div class="row gx-3">
                    <div class="col-md-6">
                        {{ user_info }}
                    </div>
                </div>
            </div>
            <div class="row mb-4">
                <div class="col-md-6">
                    <label for="id_legalization_date" class="form-label">Fecha de legalización:</label>
                    {{ invoice_legalization_form.legalization_date }}
                </div>
                <div class="col-md-6">
                    <label for="id_departure_date" class="form-label">Fecha de salida:</label>
                    {{ invoice_legalization_form.departure_date }}
                </div>
            </div>
            <div class="mb-4">
                <label for="id_dependency" class="form-label">Dependencia:</label>
                {{ invoice_legalization_form.dependency }}
            </div>
            <div class="mb-4">
                <label for="id_destination_city" class="form-label">Ciudad de destino:</label>
                {{ invoice_legalization_form.destination_city }}
            </div>
            <div class="mb-4">
                <label for="id_reason_trip" class="form-label">Motivo de viaje:</label>
                {{ invoice_legalization_form.reason_trip }}
            </div>
    <!--
        <h2 class="mt-5"> Relación de gastos </h2>
            <div class="mb-4">
                <div id="expense-container" class="row">
                    <div class="col">
                        <div class="row g-3">
                            <div class="col">
                                <label for="rubro" class="form-label">Rubro:</label>
                                {{ expense_ratio_form.rubro }}
                            </div>
                            <div class="col">
                                <label for="proveedor" class="form-label">Proveedor:</label>
                                {{ expense_ratio_form.proveedor }}
                            </div>
                            <div class="col">
                                <label for="nit" class="form-label">Nit:</label>
                                {{ expense_ratio_form.nit }}
                            </div>
                            <div class="col">
                                <label for="concepto" class="form-label">Concepto:</label>
                                {{ expense_ratio_form.concepto }}
                            </div>
                            <div class="col">
                                <label for="moneda" class="form-label">Moneda:</label>
                                {{ expense_ratio_form.advance_currency }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <button type="button" onclick="addExpense()" class="btn btn-primary mb-4">Agregar Gasto</button>
    -->
            
            <div class="mb-4">
                {{ balance_discount_autorization_form }}
            </div>
            <div class="mb-4">
                {{ bank_information }}
            </div>
            <div class="mb-4">
                {{ observations }}
            </div>
            <div class="mb-4">
                <h3>Documentos</h3>
                {{ upload_documents }}
            </div>
            <div class="text-center">
                <button type="submit" class="btn btn-success">Enviar</button>
            </div>
            
        </form>
    </main>


    <script>
        function addExpense() {
            
            var expenseContainer = document.querySelector('#expense-container');
            var newExpenseContainer = document.createElement('div');
            newExpenseContainer.className = 'row g-3';
            newExpenseContainer.innerHTML = `
                <div class="col">
                    <label for="rubro" class="form-label">Rubro:</label>
                    {{ expense_ratio_form.rubro }}
                </div>
                <div class="col">
                    <label for="proveedor" class="form-label">Proveedor:</label>
                    {{ expense_ratio_form.proveedor }}
                </div>
                <div class="col">
                    <label for="nit" class="form-label">Nit:</label>
                    {{ expense_ratio_form.nit }}
                </div>
                <div class="col">
                    <label for="concepto" class="form-label">Concepto:</label>
                    {{ expense_ratio_form.concepto }}
                </div>
                <div class="col">
                    <label for="moneda" class="form-label">Moneda:</label>
                    {{ expense_ratio_form.advance_currency }}
                </div>
            `;
            expenseContainer.appendChild(newExpenseContainer);
        }
    </script>

    {% endblock %}
</body>

</html>

requests_mgmt/templates/requests/create_invoice_request.html
{% extends "layouts/base.html" %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} Facturas {% endblock %}</title>
    <style>
        .main-container {
            padding: 20px;
            background-color: #f8f9fa;
        }
        .card-custom {
            background-color: #ffffff;
            border: 1px solid #dee2e6;
            transition: box-shadow 0.3s ease;
        }
        .card-custom:hover {
            box-shadow: 0 0 11px rgba(33,33,33,.2);
        }
        .btn-custom {
            background-color: #1E4072;
            color: white;
        }
        .btn-custom:hover {
            background-color: #16345a;
            color: white;
        }
        .card-header-custom {
            background-color: #1E4072;
            color: white;
        }
    </style>
</head>
<body>
    {% block content %}
    {% include "sidemenu.html" %}
    <div class="container main-container">
        <h1 class="mb-4">Gestión de Facturas</h1>
        <div class="card card-custom mb-4">
            <div class="card-header card-header-custom">
                Cargar Nuevos Documentos
            </div>
            <div class="card-body">
                <form>
                    <div class="mb-3">
                        <label for="invoiceFile" class="form-label">Subir Factura</label>
                        <input class="form-control" type="file" id="invoiceFile">
                    </div>
                    <div class="mb-3">
                        <label for="additionalDocs" class="form-label">Subir Documentos Adicionales</label>
                        <input class="form-control" type="file" id="additionalDocs" multiple>
                    </div>
                    <div class="text-center">
                        <button type="submit" class="btn btn-success">Enviar</button>
                    </div>
                    
                </form>
            </div>
        </div>
        
        
    </div>
    {% endblock %}
</body>
</html>